import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "./_layout/Header";
import Footer from "./_layout/Footer";
import { Toaster } from "react-hot-toast";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const rubik = localFont({
  src: "./fonts/Rubik.ttf",
  variable: "--font-rubik",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Test",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${rubik.variable} ${geistMono.variable} ${geistSans.variable} antialiased`}
      >
        <Header />
        <Toaster position="top-center" containerClassName="mt-4" />

        {children}
        <Footer />
      </body>
    </html>
  );
}
